[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_token = "H2aVd4L4Fnc3zs9oUd51vpjjYjyMPNT3yyLsH6RGCWzi"
solana_lst = "PNy1kV6FqrGJTWfvLVWCiM2MRJjfNVHRYEPnmwcsKNE"
spl_token_example = "1W9jnwRKMozdqr36xQmD8NSKCHT7cuE9kHmFZX5Q9jz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hotingyuen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
